name: Publish react to Azure

on:
    push:
        branches: [ main ]
        
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: seasonal-react
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: build and test
      run: |
        npm ci
        npm run build
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: Publish to Azure
      uses: azure/CLI@v1
      working-directory: ./build
      with:
        inlineScript: |
            az storage blob upload-batch --account-name seasonal  --auth-mode key -d '$web' -s .
    - name: logout
      run: |
            az logout
      if: always()
